/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Mancare.Restaurant;
import datele_mele.DateCity;
import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author grigo_zpv1keq
 */
public class RestauranteGUI extends  JInternalFrame {

     DefaultListModel<String> listModel = new DefaultListModel<>(); // model pt jlist
     int selectedValue; 
     String valoare;
     int pretmeniulzilei=25;
     double pret;
     
    public RestauranteGUI() {
        initComponents();
        DateCity.addVectori(); // introduci datele in interfata 
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(722, 473));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Restaurante");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Afisare optiuni");

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("Afisare fara filtru");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("animale de companie");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("persoane fumatoare");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("terasa");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("codvestimentar");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("factura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("meniul zilei");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("Bauturi");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jRadioButton7.setText("mic dejun");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setText("pranz");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setText("cina");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         listModel.clear(); // stergi ceea ce ai inainte 
        for(int i=0;i<10;i++){
            listModel.addElement(DateCity.vecRestaurant.get(i).nume); // adaugi numele cafenelelor in lista 
        }
        jList1.setModel(listModel);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
         valoare = jList1.getSelectedValue(); 
        for(int i=0;i<10;i++){
            String nume=DateCity.vecRestaurant.get(i).nume;
            if(nume==valoare){
                 String specificatii = DateCity.vecRestaurant.get(i).Afiseazainterfata();
                 jTextArea1.setText(DateCity.vecRestaurant.get(i).toString()+"\n"+specificatii);
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
listModel.clear();
      boolean animaldecompanie= jRadioButton1.isSelected();
   for(int i=0;i<10;i++)
   {
           
            if(animaldecompanie && DateCity.vecRestaurant.get(i).animaldecompanie){
              listModel.addElement(DateCity.vecRestaurant.get(i).nume);
      }
   }

 updateRestaurantList();
    jList1.setModel(listModel);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
      listModel.clear();
      boolean persoanefumatoare= jRadioButton2.isSelected();
   for(int i=0;i<10;i++)
   {
           
            if(persoanefumatoare && DateCity.vecRestaurant.get(i).persoanefumatoare){
              listModel.addElement(DateCity.vecRestaurant.get(i).nume);
      }
   }

 updateRestaurantList();
    jList1.setModel(listModel);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        listModel.clear();
      boolean terasa= jRadioButton3.isSelected();
   for(int i=0;i<10;i++)
   {
           
            if(terasa && DateCity.vecRestaurant.get(i).terasa){
              listModel.addElement(DateCity.vecRestaurant.get(i).nume);
      }
   }

 updateRestaurantList();
    jList1.setModel(listModel);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        listModel.clear();
      boolean codvestimentar= jRadioButton4.isSelected();
   for(int i=0;i<10;i++)
   {
           
            if(codvestimentar && DateCity.vecRestaurant.get(i).codvestimentar){
              listModel.addElement(DateCity.vecRestaurant.get(i).nume);
      }
   }

 updateRestaurantList();
    jList1.setModel(listModel);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        if (jRadioButton6.isSelected()) {
        int indexRestaurantSelectata = jList1.getSelectedIndex();
        if (indexRestaurantSelectata >= 0 && indexRestaurantSelectata < DateCity.vecRestaurant.size()) {
             double pretRestaurantSelectat= DateCity.vecRestaurant.get(indexRestaurantSelectata).getPret()[3];
            jLabel7.setText(" " +pretRestaurantSelectat+ " ron");
        } else {
            jLabel7.setText("Niciun restaurant  selectat.");
        }
    } else {
        jLabel7.setText(""); // Șterge conținutul etichetei când butonul radio nu este selectat
    }
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
       if (jRadioButton5.isSelected()) {
        int indexRestaurantSelectata = jList1.getSelectedIndex();
        if (indexRestaurantSelectata >= 0 && indexRestaurantSelectata < DateCity.vecRestaurant.size()) {
            double pretRestaurantSelectat = pretmeniulzilei;
            jLabel3.setText(" " +pretRestaurantSelectat+ " ron");
        } else {
            jLabel3.setText("Niciun restaurant  selectat.");
        }
    } else {
        jLabel3.setText(""); // Șterge conținutul etichetei când butonul radio nu este selectat
    }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
       if (jRadioButton7.isSelected()) {
        int indexRestaurantSelectata = jList1.getSelectedIndex();
        if (indexRestaurantSelectata >= 0 && indexRestaurantSelectata < DateCity.vecRestaurant.size()) {
             double pretRestaurantSelectat= DateCity.vecRestaurant.get(indexRestaurantSelectata).getPret()[0];
            jLabel4.setText(" " +pretRestaurantSelectat+ " ron");
        } else {
            jLabel4.setText("Niciun restaurant  selectat.");
        }
    } else {
        jLabel4.setText(""); // Șterge conținutul etichetei când butonul radio nu este selectat
    }
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
      if (jRadioButton8.isSelected()) {
        int indexRestaurantSelectata = jList1.getSelectedIndex();
        if (indexRestaurantSelectata >= 0 && indexRestaurantSelectata < DateCity.vecRestaurant.size()) {
             double pretRestaurantSelectat= DateCity.vecRestaurant.get(indexRestaurantSelectata).getPret()[1];
            jLabel5.setText(" " +pretRestaurantSelectat+ " ron");
        } else {
            jLabel5.setText("Niciun restaurant  selectat.");
        }
    } else {
        jLabel5.setText(""); // Șterge conținutul etichetei când butonul radio nu este selectat
    }
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
       if (jRadioButton9.isSelected()) {
        int indexRestaurantSelectata = jList1.getSelectedIndex();
        if (indexRestaurantSelectata >= 0 && indexRestaurantSelectata < DateCity.vecRestaurant.size()) {
             double pretRestaurantSelectat= DateCity.vecRestaurant.get(indexRestaurantSelectata).getPret()[2];
            jLabel6.setText(" " +pretRestaurantSelectat+ " ron");
        } else {
            jLabel6.setText("Niciun restaurant  selectat.");
        }
    } else {
        jLabel6.setText(""); // Șterge conținutul etichetei când butonul radio nu este selectat
    }
    }//GEN-LAST:event_jRadioButton9ActionPerformed
private void calculeazaPretComanda() {
      boolean isJRadioButton5Selected = jRadioButton5.isSelected();
        boolean isJRadioButton6Selected = jRadioButton6.isSelected();
          boolean isJRadioButton7Selected = jRadioButton7.isSelected();
           boolean isJRadioButton8Selected = jRadioButton8.isSelected();
            boolean isJRadioButton9Selected = jRadioButton9.isSelected();
        pret=0;
    for(int i=0;i<10;i++)
    {
    if(valoare==DateCity.vecRestaurant.get(i).nume)
    {
     if (isJRadioButton5Selected) {
            pret+= pretmeniulzilei;
        }

        if (isJRadioButton7Selected) {
            pret += DateCity.vecRestaurant.get(i).getPret()[0];
        }
 if (isJRadioButton8Selected) {
            pret += DateCity.vecRestaurant.get(i).getPret()[1];
        }
    if (isJRadioButton9Selected) {
            pret += DateCity.vecRestaurant.get(i).getPret()[2];
        }
    if (isJRadioButton6Selected) {
            pret += DateCity.vecRestaurant.get(i).getPret()[3];
        }
    }
    }
    jTextArea1.setText(" comanda a fost efectuata si acesta este pretul  "+pret);

   Factura();
   MenuPrincipal.setBill(pret);
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      calculeazaPretComanda();
      
    }//GEN-LAST:event_jButton3ActionPerformed
private void updateRestaurantList() {
    listModel.clear();

    for (int i = 0; i < 10; i++) {
        boolean meetsCriteria = true;

        if (jRadioButton1.isSelected() && !DateCity.vecRestaurant.get(i).animaldecompanie) {
            meetsCriteria = false;
        }

        if (jRadioButton2.isSelected() && !DateCity.vecRestaurant.get(i).persoanefumatoare) {
            meetsCriteria = false;
        }

        if (jRadioButton3.isSelected() && !DateCity.vecRestaurant.get(i).terasa) {
            meetsCriteria = false;
        }
        if (jRadioButton4.isSelected() && !DateCity.vecRestaurant.get(i).codvestimentar) {
            meetsCriteria = false;
        }

        if (meetsCriteria) {
            listModel.addElement(DateCity.vecRestaurant.get(i).nume);
        }
    }
}
  private void Factura(){
     Restaurant restaurant =null;
        JFrame fereastraSecundara = new JFrame("Factura ta");
        JLabel label = new JLabel();
        
        for(int i=0; i<10;i++){
        String nume=DateCity.vecRestaurant.get(i).nume;
            if(nume==valoare){
               restaurant=DateCity.vecRestaurant.get(i);
            }
    }
  

       
       StringBuilder result = new StringBuilder();
       result.append("<html>------Factura de la  Restaurantul    ").append(restaurant.nume).append(" -----<br>");
       if(jRadioButton5.isSelected())
       result.append("<br>Meniul zilei..................................").append(pretmeniulzilei).append("<br>" );
       if(jRadioButton7.isSelected())
       result.append("<br>Mic dejun....................................").append(restaurant.pret[0]).append("<br>");
       if(jRadioButton8.isSelected())
        result.append("<br>Pranz....................................").append(restaurant.pret[1]).append("<br>");
       if(jRadioButton9.isSelected())
         result.append("<br>Cina....................................").append(restaurant.pret[2]).append("<br>");
         if(jRadioButton6.isSelected())
          result.append("<br>Bauturi....................................").append(restaurant.pret[3]).append("<br>");
       result.append("---------------------------------------------------------------<br>");
       result.append("TOTAL:                                ").append(pret).append("<br></html>");

      
        label.setText(result.toString());
        label.setFont(new Font("Times new roman",Font.BOLD,18));
        fereastraSecundara.add(label);
        fereastraSecundara.setSize(700, 600);
        fereastraSecundara.setLocationRelativeTo(this); // Deschide fereastra secundară în centrul ferestrei principale
        fereastraSecundara.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Închide doar fereastra secundară la închiderea ei
        fereastraSecundara.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
